# Generated by Django 4.1.4 on 2022-12-31 16:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_remove_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='descript',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
